### ISSUE TITLE
Unable to Restore a Heroku Instance from Database Dump

### ISSUE THREAD

**Issue by Tookmund** [hackumass/hackerforce#18]
I've been taking regular backups of our hackerforce instance, generated with:
```
heroku run -a "$HACKERFORCE" python manage.py dumpdata -- > "$(date --iso-8601=seconds).json"
```
following the advice in `docs/dumpdata.md`.
I attempted  to restore one  of those backups to another test instance of hackerforce on heroku:

```
heroku run -a hackerforcebackuptest -- python manage.py loaddata - -e contenttypes < hackerforce-backups/2021-01-09T15\:48\:34-05\:00.json
```
Instead of restoring this backup to the new instance, this command output part of the dump file (not reproducing the output here since it seems to include session cookies) 

Heroku logs show only the following and no changes appear to have been made to the test instance (email edited for privacy):
```
2021-01-09T22:01:19.879350+00:00 app[api]: Starting process with command `python manage.py loaddata - -e contenttypes` by user my@email
2021-01-09T22:01:37.458201+00:00 heroku[run.7979]: State changed from starting to up
2021-01-09T22:01:37.753265+00:00 heroku[run.7979]: Awaiting client
2021-01-09T22:01:37.790378+00:00 heroku[run.7979]: Starting process with command `python manage.py loaddata - -e contenttypes`
2021-01-09T22:01:45.009154+00:00 heroku[run.7979]: Client connection closed. Sending SIGHUP to all processes
2021-01-09T22:01:45.011656+00:00 heroku[run.7979]: Process exited with status 1
2021-01-09T22:01:45.055185+00:00 heroku[run.7979]: State changed from up to complete
```

I assume I must be doing something wrong here, so I'd appriciate any advice on how I can backup and restore my hackerforce instance.

For now, I'm also taking full database dumps, but those take up more space, so I'd prefer to use the dump/load system if possible.

**Comment by jwoglom** [comment]
From what I remember, I ran into a similar problem and the issue had to do with the fact that I couldn't directly pipe the file's contents into the heroku cli.

Try doing something like:
* upload the json file you want to load as a private gist, or somewhere else that you can access it publicly through some url
* use heroku run to open a bash shell, and then use curl or wget to download the json dump into the local filesystem on the heroku instance
* then, in the same shell, use manage.py loaddata on the json file which is now in the filesystem

**Comment by Tookmund** [comment]
I did some more research into this and heroku run can actually take input from stdin like this if you use `--no-tty`
I've now been able to successfully restore a backup using the following:
```
heroku run --no-tty -a myhackerforce -- python manage.py loaddata -e contenttypes --format=json - < mybackup.json
```

Going to add a wiki page on this now that I've gotten it to work, but one strange thing is that all my backups begin with the line:
```
Downloading the sponsorship packet to: {} /app/website/static/sponsorship.pdf
```
which makes the import process fail, but once removed they work fine.
I'll have to look into whats adding this to the backup file.

**Comment by jwoglom** [comment]
Pretty sure that's a line in settings.py where it tries to download the packet if it doesn't exist. You can probably comment out the print line or add an if statement around it
